### ISSUE TITLE
FD trinket swap broken after update

### ISSUE THREAD

**Issue by perks** [Rottenbeer/ItemRack#103] opened 2020-06-12 01:07 UTC
Hey, after the update change to autoqueing, autoqueing trinkets for swap during FD no longer seems to trigger.

**Comment by Rottenbeer** [comment] 2020-06-12 11:52
Hey
- Did it work with 3.40 or which version did work for you?
- Did you check "Auto queue this slot" for the item after 3.40?

**Comment by perks** [comment] 2020-06-12 14:27
Yeah I downgraded to 3.40 and it started working again. Tried toggling the "auto queue this slot" after a /reload and also exiting and reinstalling the addon in a fresh session.

**Comment by blastehh** [comment] 2020-06-12 14:58
Are you able to reproduce this while recording it?

**Comment by perks** [comment] 2020-06-12 15:52
Ill try to get some recordings posted tonight!

**Comment by Rottenbeer** [comment] 2020-06-13 14:01
Please download the latest master from https://github.com/Rottenbeer/ItemRack and check if it works with this version.

**Comment by perks** [comment] 2020-06-13 14:47
So it seems to only be effecting the second slot. I tried with the update and the same behaviour occurs -- i included a different trinket to see whether it was the new trinket from ZG that causes this but didnt seem so. I am running a weak aura that lets me know if FD is resisted (also combat text displays drop of combat).

3.40 both slots working: https://streamable.com/ohkrxf
3.42 not working: https://streamable.com/tmemm6
3.43 not working: https://streamable.com/hl4fwz
3.43 different trinket not working: https://streamable.com/8k8nb0

Thanks for taking the time to triage this!

**Comment by blastehh** [comment] 2020-06-13 15:09
Did you uncheck and re-check the "Auto queue this slot" option at any point after the upgrade to the new version? If not, that could cause issues.
Will see if I can spot anything further though.

If you alt+click your trinket slot in the character screen, it will give you a trinket widget, this should show if trinkets are queued for swap with an icon in the top left corner of the widget.

**Comment by perks** [comment] 2020-06-13 15:18
I did toggle it a couple of times when testing

When enabling itemrack's queue swap here is what is appearing: 
![image](https://user-images.githubusercontent.com/1820298/84572400-a0d87b00-ad67-11ea-8f2e-0485f38b3ca2.png)

So top slot is correctly showing the icon of a trinket to swap to, where as the bottom slot only shows a gear

**Comment by blastehh** [comment] 2020-06-13 15:22
Can you alt+click the bottom slot widget so the cog gets removed and re-added?
The swap should also work out of combat if the current equipped trinket is on cd.

**Comment by perks** [comment] 2020-06-13 15:24
@blastehh  @Rottenbeer it seems removing and re-adding the slot fixes this issue!

**Comment by blastehh** [comment] 2020-06-13 15:25
I'm 99% sure that this was because your settings carried over from 3.40 where the value for the checkbox was incorrect. Toggling it gives it the correct value.

**Comment by Rottenbeer** [comment] 2020-06-13 15:47
Very nice to hear that the issue is fixed.
I wonder if we should add some kind of migration for such things in the future.im closing the issue now.
Thanks for your help!

**Closed by Rottenbeer** 2020-06-13 15:47 UTC
